### ISSUE TITLE
Can't install plugin with logstash release >=8.5.1

### ISSUE THREAD

**Issue by maederm** [cherweg/logstash-input-s3-sns-sqs#77]
Hi

I can't install the plugin with logstash >=8.5.1. It just hangs during the `bin/logstash-plugin install` command.

I can reproduce it in logstash releases 8.5.1, 8.5.2, 8.5.3 and 8.6.0.

Here is an example docker-compose.yml file to see the issue.

```yaml
version: '2.3'
services:
  ls860:
    image: docker.elastic.co/logstash/logstash:8.6.0
    command: bin/logstash-plugin install logstash-input-s3-sns-sqs
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
```

Cheers, maederm
